#!/usr/bin/env python3
"""Generate one illustration per scanner summary with Google's Gemini image
model ("Nano Banana") and wire it into the findings files.

Usage:
    GEMINI_API_KEY=... python3 generate_summary_visuals.py <findings-or-ai-insights-dir> [options]

    --dry-run        list what would be generated, no API calls, no writes
    --force          regenerate even when an image already exists
    --only NAME      limit to one or more scanners (repeatable), e.g. --only tech-stack-scan
    --model NAME     Gemini image model (default: gemini-3-pro-image-preview)
    --aspect RATIO   aspect ratio for the image (default: 16:9)
    --sleep SECONDS  pause between API calls (default: 2.0)
    --no-render      skip re-rendering ai-insights/index.html afterwards

The API key is read from the GEMINI_API_KEY environment variable
(GOOGLE_API_KEY is accepted as a fallback). Nothing else is needed:
standard library only, like the other Sokrates scripts.

For every scanner findings JSON (``<scanner>.json``) in the ai-insights
folder that has a ``summary``:

  1. If ``visuals/<scanner>.<ext>`` already exists on disk it is kept
     (the file is the source of truth, not the JSON field); the JSON gets the
     ``summary_visual`` field if it is missing. Use --force to regenerate.
  2. Otherwise a short visual prompt is built from the scanner's purpose,
     the target name and the summary text, the image model is called, and the
     result is saved as ``visuals/<scanner>.png`` (or ``.jpeg``, whatever the
     model returns).
  3. The findings JSON gets::

         "summary_visual": {
           "file": "visuals/<scanner>.png",
           "credit": "Illustration generated by Google Gemini (<model>)",
           "generated_at": "...",
           "prompt": "..."
         }

     The AI Insights Explorer shows the image at the end of the foldable
     summary block, so index.html is re-rendered at the end (unless
     --no-render), using the scan-core render script.

The images are deliberately mostly visual - a calm illustration that tells
the summary's story with a few short key words, not an infographic. Numbers,
titles and dates are kept out of the picture.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_MODEL = "gemini-3-pro-image-preview"
INSIGHTS_DIR_NAME = "ai-insights"
VISUALS_DIR_NAME = "visuals"
IMAGE_EXTENSIONS = (".png", ".jpeg", ".jpg", ".webp")

SCAN_CORE = Path(__file__).resolve().parent.parent / "scanners" / "sokrates-scan-core"
RENDER_SCRIPT = SCAN_CORE / "scripts" / "render_findings.py"
SCANNERS_META = SCAN_CORE / "templates" / "scanners.json"

# What each scanner is about, as a visual motif hint for the image model.
# Falls back to the scanner description from scanners.json for unknown scanners.
MOTIFS = {
    "tech-stack-scan": "layered building blocks, tools and libraries fitting together into one stack",
    "functionality-scan": "a product in use: entry points, screens or commands flowing into what the software does for its users",
    "architecture-scan": "a blueprint of components with clear boundaries and arrows showing how they connect",
    "risk-synthesis-scan": "a landscape with a few glowing hotspots and cracks that need attention, otherwise stable ground",
    "cicd-scan": "a conveyor or pipeline carrying code through build, test and release stages towards users",
    "reliability-scan": "a structure that stays standing while one part fails: firewalls between compartments, a safety net, a spring that bends and recovers",
    "performance-scan": "flow through a system with one narrow bottleneck glowing, wide parallel channels elsewhere, a gauge or stopwatch",
    "observability-scan": "instruments, gauges and signal lines revealing what a system is doing inside",
    "security-design-scan": "walls, gates and locks marking trust boundaries between an inside and an outside",
    "security-scan": "a magnifying glass over code lines, spotting a few flagged fragments in an otherwise clean field",
    "domain-language-scan": "a map of distinct territories for the core concepts, a few borders blurred or overlapping, no place names",
    "evolution-scan": "a timeline or growth rings showing eras, growth and shifting centres of activity",
}

STYLE = (
    "Create a single, calm, aesthetically pleasing illustration that tells the story of the analysis "
    "summary below - a reader should grasp its one or two big ideas at a glance. Text is welcome but "
    "sparse: a few short labels or key words (roughly 3 to 8, one to three words each) that anchor the "
    "story; no sentences, no numbers, no dates, no titles, no legends, no dense diagrams or flowcharts, "
    "no dashboards or screenshots. Let shapes, metaphor, composition and colour carry most of the meaning. "
    "Style: polished flat vector illustration, crisp outlines, minimal shading, generous margins so nothing "
    "touches the edges, a disciplined palette of deep blue, teal, soft green and warm orange accents on a "
    "light background. Uncluttered - a few well-chosen elements and plenty of negative space. "
    "No photorealism, no 3D render, no clip-art collage, no people's faces."
)


# ---------- helpers ----------

def load_scanner_descriptions() -> dict:
    try:
        doc = json.loads(SCANNERS_META.read_text())
    except (OSError, json.JSONDecodeError):
        return {}
    return {s.get("id"): s.get("description", "") for s in doc.get("scanners", []) if isinstance(s, dict)}


def resolve_insights_dir(arg: str) -> Path:
    p = Path(arg)
    if p.name != INSIGHTS_DIR_NAME and (p / INSIGHTS_DIR_NAME).is_dir():
        return p / INSIGHTS_DIR_NAME
    return p


def load_findings(insights_dir: Path):
    """Yield (path, doc) for scanner findings files (combined-report is skipped)."""
    for path in sorted(insights_dir.glob("*.json")):
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(doc, dict) or "scanner" not in doc or "findings" not in doc:
            continue
        if doc.get("scanner") == "combined":
            continue
        yield path, doc


def existing_image(visuals_dir: Path, scanner: str):
    for ext in IMAGE_EXTENSIONS:
        candidate = visuals_dir / f"{scanner}{ext}"
        if candidate.is_file():
            return candidate
    return None


def strip_markup(text: str) -> str:
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\*\*([^*]*)\*\*", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def build_prompt(doc: dict, descriptions: dict, max_chars: int = 1000) -> str:
    scanner = doc.get("scanner", "")
    target = (doc.get("target") or {}).get("name") or "the analyzed software"
    motif = MOTIFS.get(scanner) or descriptions.get(scanner) or scanner.replace("-", " ")
    summary = strip_markup(doc.get("summary", ""))
    if len(summary) > max_chars:
        cut = summary[:max_chars]
        summary = cut[: cut.rfind(". ") + 1] if ". " in cut else cut
    return "\n".join([
        STYLE,
        f"Visual motif for this kind of analysis ({scanner}): {motif}.",
        f"Subject: the software project '{target}'.",
        f"Story to tell (pick the essence, do not transcribe it): {summary}",
    ])


# ---------- Gemini API ----------

def call_gemini_image(api_key: str, model: str, prompt: str, aspect: str, timeout: int = 240):
    """Return (image_bytes, mime_type). Raises RuntimeError on failure."""
    endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
    payload = {
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {
            "responseModalities": ["IMAGE"],
            "imageConfig": {"aspectRatio": aspect},
        },
    }
    req = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json", "x-goog-api-key": api_key},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read()
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {e.code} from Gemini: {detail[:800]}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"network error calling Gemini: {e}") from e

    data = json.loads(body.decode("utf-8"))
    for cand in data.get("candidates") or []:
        for part in (cand.get("content") or {}).get("parts") or []:
            inline = part.get("inlineData") or part.get("inline_data")
            if inline and inline.get("data"):
                return base64.b64decode(inline["data"]), inline.get("mimeType") or inline.get("mime_type") or ""
    raise RuntimeError("no image data in Gemini response: " + json.dumps(data)[:600])


def extension_for(image_bytes: bytes, mime: str) -> str:
    if image_bytes.startswith(b"\x89PNG"):
        return ".png"
    if image_bytes.startswith(b"\xff\xd8"):
        return ".jpeg"
    if image_bytes[:4] == b"RIFF" and image_bytes[8:12] == b"WEBP":
        return ".webp"
    return {"image/jpeg": ".jpeg", "image/webp": ".webp"}.get(mime, ".png")


# ---------- per-scanner workflow ----------

def write_doc(path: Path, doc: dict):
    path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def process(path: Path, doc: dict, visuals_dir: Path, descriptions: dict, args, api_key: str) -> str:
    scanner = doc["scanner"]
    if not doc.get("summary"):
        return "skip (no summary)"
    credit = f"Illustration generated by Google Gemini ({args.model})"

    image = existing_image(visuals_dir, scanner)
    if image and not args.force:
        rel = f"{VISUALS_DIR_NAME}/{image.name}"
        current = doc.get("summary_visual") or {}
        if current.get("file") == rel:
            return "skip (image present)"
        if not args.dry_run:
            doc["summary_visual"] = {"file": rel, "credit": current.get("credit", credit)}
            write_doc(path, doc)
        return "linked existing image"

    prompt = build_prompt(doc, descriptions)
    if args.dry_run:
        return f"dry-run (would generate; prompt {len(prompt)} chars)"

    image_bytes, mime = call_gemini_image(api_key, args.model, prompt, args.aspect)
    visuals_dir.mkdir(parents=True, exist_ok=True)
    for ext in IMAGE_EXTENSIONS:  # drop a stale image in another format
        stale = visuals_dir / f"{scanner}{ext}"
        if stale.exists():
            stale.unlink()
    out = visuals_dir / f"{scanner}{extension_for(image_bytes, mime)}"
    out.write_bytes(image_bytes)
    doc["summary_visual"] = {
        "file": f"{VISUALS_DIR_NAME}/{out.name}",
        "credit": credit,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "prompt": prompt,
    }
    write_doc(path, doc)
    return f"generated {out.name} ({len(image_bytes) // 1024} KB)"


def render(insights_dir: Path) -> bool:
    if not RENDER_SCRIPT.is_file():
        print(f"note: render script not found at {RENDER_SCRIPT}, index.html not refreshed", file=sys.stderr)
        return False
    result = subprocess.run([sys.executable, str(RENDER_SCRIPT), str(insights_dir)])
    return result.returncode == 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__)
    ap.add_argument("target", help="_sokrates/findings or _sokrates/findings/ai-insights folder")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true", help="regenerate existing images")
    ap.add_argument("--only", action="append", default=[], metavar="SCANNER")
    ap.add_argument("--model", default=DEFAULT_MODEL)
    ap.add_argument("--aspect", default="16:9")
    ap.add_argument("--sleep", type=float, default=2.0)
    ap.add_argument("--no-render", action="store_true")
    args = ap.parse_args(argv)

    insights_dir = resolve_insights_dir(args.target)
    if not insights_dir.is_dir():
        print(f"error: not a folder: {insights_dir}", file=sys.stderr)
        return 2
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key and not args.dry_run:
        print("error: GEMINI_API_KEY (or GOOGLE_API_KEY) environment variable is not set", file=sys.stderr)
        return 2

    targets = [(p, d) for p, d in load_findings(insights_dir) if not args.only or d["scanner"] in args.only]
    if not targets:
        print(f"error: no scanner findings files in {insights_dir}", file=sys.stderr)
        return 2
    visuals_dir = insights_dir / VISUALS_DIR_NAME
    descriptions = load_scanner_descriptions()
    print(f"Processing {len(targets)} scanner(s) in {insights_dir} ...")

    generated = errors = 0
    for i, (path, doc) in enumerate(targets):
        try:
            status = process(path, doc, visuals_dir, descriptions, args, api_key or "")
        except Exception as e:  # noqa: BLE001 - keep going on per-scanner errors
            status, errors = f"ERROR: {e}", errors + 1
        print(f"[{i + 1}/{len(targets)}] {doc['scanner']}: {status}", flush=True)
        if status.startswith("generated"):
            generated += 1
            if args.sleep and i + 1 < len(targets):
                time.sleep(args.sleep)

    print(f"\nDone. {generated} image(s) generated, {errors} error(s).")
    if not args.dry_run and not args.no_render:
        render(insights_dir)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
