#!/usr/bin/env python3
"""Merge multiple Sokrates AI scanner findings files into one combined document.

Takes the ai-insights directory (or explicit JSON files) and writes
combined-report.json — a schema-conformant findings document (scanner
"combined") concatenating all findings, so the standard tooling composes:
validate_findings.py re-verifies every citation in one pass and
diff_findings.py compares two merged runs. Human-facing browsing is the job
of the HTML explorer (render_findings.py), which merges across scanners
itself — no markdown is produced.

Files that don't have the findings shape (no "scanner" + "findings" keys)
are skipped with a note; a previous combined-report.json is skipped too so
re-merging a directory never self-ingests.

Usage:
  python3 merge_findings.py <ai-insights-dir>          [-o combined-report.json]
  python3 merge_findings.py a.json b.json [c.json...]  [-o combined-report.json]

Given `_sokrates/reports/`, the script descends into `ai-insights/`.
Without -o, writes combined-report.json into that directory (or the first
file's directory).
"""

import argparse
import json
import sys
from pathlib import Path

# Deliberately duplicated across merge/diff: each script stays a single
# standalone file that can be copied or invoked in isolation.
SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


def load_findings_docs(paths):
    docs, skipped = [], []
    for path in paths:
        try:
            doc = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            skipped.append((path, "unreadable or not JSON"))
            continue
        if not isinstance(doc, dict) or "scanner" not in doc or "findings" not in doc:
            skipped.append((path, "not a findings file"))
            continue
        if doc.get("scanner") == "combined":
            skipped.append((path, "previous combined output"))
            continue
        doc["_path"] = path
        docs.append(doc)
    docs.sort(key=lambda d: d.get("scanner", ""))
    return docs, skipped


def build_combined_doc(docs) -> dict:
    """A schema-conformant findings document concatenating all scanners' findings."""
    all_findings = [f for d in docs for f in d.get("findings", [])]
    seen = set()
    for f in all_findings:
        fid = f.get("id", "")
        if fid in seen:
            print(f"warning: duplicate finding id across scanners: {fid}", file=sys.stderr)
        seen.add(fid)

    src_roots = {d.get("target", {}).get("src_root", "") for d in docs}
    if len(src_roots) > 1:
        print(f"warning: inputs disagree on target.src_root {sorted(src_roots)}; "
              "using the first — evidence paths from other roots may not re-validate",
              file=sys.stderr)

    counts = severity_counts(all_findings)
    scanner_names = [d.get("scanner", "?") for d in docs]
    summary = (f"Combined findings of {len(docs)} scanners ({', '.join(scanner_names)}): "
               f"{len(all_findings)} findings — {format_counts(counts)}. "
               "Generated by merge_findings.py; see each scanner's own file for its narrative summary.")
    return {
        "scanner": "combined",
        "scanner_version": "1.0",
        "analyzed_at": max((d.get("analyzed_at", "") for d in docs)),
        "target": {k: v for k, v in docs[0].get("target", {}).items()},
        "summary": summary,
        "stats": {
            "scanners": {
                d.get("scanner", "?"): {
                    "scanner_version": d.get("scanner_version", ""),
                    "analyzed_at": d.get("analyzed_at", ""),
                    "findings": len(d.get("findings", [])),
                } for d in docs
            },
            "severity_totals": counts,
        },
        "findings": all_findings,
    }


def severity_counts(findings):
    counts = {}
    for f in findings:
        sev = f.get("severity", "info")
        counts[sev] = counts.get(sev, 0) + 1
    return counts


def format_counts(counts):
    parts = []
    for sev in ("critical", "high", "medium", "low", "info"):
        if counts.get(sev):
            parts.append(f"{counts[sev]} {sev}")
    return ", ".join(parts) if parts else "none"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+",
                    help="The ai-insights directory, or two or more findings JSON files")
    ap.add_argument("-o", "--output", help="Output JSON path")
    args = ap.parse_args()

    first = Path(args.inputs[0])
    if len(args.inputs) == 1 and first.is_dir():
        if first.name != "ai-insights" and (first / "ai-insights").is_dir():
            first = first / "ai-insights"
        paths = sorted(first.glob("*.json"))
        out_dir = first
    else:
        paths = [Path(p) for p in args.inputs]
        out_dir = paths[0].parent
    docs, skipped = load_findings_docs(paths)
    if not docs:
        print("error: no findings files found among inputs", file=sys.stderr)
        return 2
    for path, reason in skipped:
        print(f"note: skipped {path.name} ({reason})", file=sys.stderr)

    json_path = Path(args.output) if args.output else out_dir / "combined-report.json"
    combined = build_combined_doc(docs)
    json_path.write_text(json.dumps(combined, indent=2) + "\n")
    print(f"wrote {json_path} ({len(docs)} scanners, {len(combined['findings'])} findings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
